"""add tool_trace to messages

Revision ID: b65e4f125b56
Revises: 4ddcd6a2a97a
Create Date: 2026-07-20 12:05:12.205230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65e4f125b56'
down_revision: Union[str, Sequence[str], None] = '4ddcd6a2a97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_trace', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_trace')
    # ### end Alembic commands ###
