"""init

Revision ID: f7fbd61a2c18
Revises: 
Create Date: 2026-05-26 16:36:18.903248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7fbd61a2c18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('inventory', 'area',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('inventory', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('price_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('stock_product_id_inventory_id_location_id_key'), 'stock', type_='unique')
    op.create_unique_constraint('uq_stock_product_inventory_location', 'stock', ['product_id', 'inventory_id', 'location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stock_product_inventory_location', 'stock', type_='unique')
    op.create_unique_constraint(op.f('stock_product_id_inventory_id_location_id_key'), 'stock', ['product_id', 'inventory_id', 'location_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('price_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('inventory', 'area',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('inventory', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###

